### ISSUE TITLE
[Feature request]: honor Next.js' `assetPrefix` when precaching assets

### ISSUE THREAD

**Issue by miltonlaufer** [serwist/serwist#198]
### Which project is this feature request for?

@serwist/next

### Describe the feature you'd like to request

When using Next.js in its "standalone" output setting, [it is recommended](https://nextjs.org/docs/pages/api-reference/next-config-js/output#automatically-copying-traced-files) to put the `public` and `.next/static` on a CDN. 
Then, in `next.config.js` one needs to set the value of `asstPrefix` with the URL of the CDN (i.e.: `https://cdn.mywebsite.com/`). Unfortunately, this setting is not honored by Serwist, so if my website URL is `https://mywebsite.com`, Serwist tries to pre-cache the `public` folder assets from, let's say, `https://mywebsite.com/images/my-image.png` instead of `https://cdn.mywebsite.com/image/my-image.png`.

### Describe the solution you'd like

Automatically adding Next.js' `assetPrefix` to any assets should be the expected behavior. 

### Describe alternatives you've considered

Both [modifyURLPrefix](https://serwist.pages.dev/docs/build/configuring/modify-url-prefix) and [manifestTransforms](https://serwist.pages.dev/docs/build/configuring/manifest-transforms) seem a viable option to do this, but it just seem too complex for something one would expect to be handled automatically.

**Comment by DuCanhGH** [comment]
https://nextjs.org/docs/app/api-reference/next-config-js/assetPrefix#set-up-a-cdn

**Comment by miltonlaufer** [comment]
Thanks for the answer. I understand Next.js doesn't automatically add the prefix for the public folder. But as the Serwist pre cache doesn't use what I introduced in the code but just transverse the public folder an assumes they will be in certain location, how can achieve the desired behavior?

**Comment by DuCanhGH** [comment]
@miltonlaufer you should use `manifestTransforms`. That left me wondering though: why the hell is it that `@serwist/next`'s internal manifest transformer runs later than the user-provided ones...

Hopefully we can get this fixed in v10 :) For now it goes something like this:

```js
// @ts-check
/** @import { Compilation } from "webpack" */
import withSerwistInit from "@serwist/next";
import path from "node:path";

/**
 * @param {Compilation} compilation The webpack compilation.
 * @param {string} originalPath The original path value.
 *
 * @returns {string} If path was not absolute, the returns path as-is.
 * Otherwise, returns path relative to the compilation's output path.
 */
const relativeToOutputPath = (compilation, originalPath) => {
  // See https://github.com/jantimon/html-webpack-plugin/pull/266/files#diff-168726dbe96b3ce427e7fedce31bb0bcR38
  if (path.resolve(originalPath) === path.normalize(originalPath)) {
    return path.relative(/** @type {string} */ (compilation.options.output.path), originalPath);
  }

  // Otherwise, return swDest as-is.
  return originalPath;
};

const assetPrefix = "https://example.com";

const basePath = "/";

// You may want to use a more robust revision to cache
// files more efficiently.
// A viable option is `git rev-parse HEAD`.
const revision = crypto.randomUUID();

const publicDir = path.resolve("public");

const withSerwist = withSerwistInit({
  cacheOnNavigation: true,
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  additionalPrecacheEntries: [{ url: "/~offline", revision }],
  manifestTransforms: [
    async (manifestEntries, comp) => {
      const compilation = /** @type {Compilation} */ (comp);
      // This path always uses forward slashes, so it is safe to use it in the following string replace.
      const publicPath = compilation.compiler.options.output?.publicPath;
      const publicDirRelativeOutput = relativeToOutputPath(compilation, publicDir);
      const publicFilesPrefix = `${publicPath}${publicDirRelativeOutput}`;
      const manifest = manifestEntries.map((m) => {
        if (m.url.startsWith(publicFilesPrefix)) m.url = path.posix.join(assetPrefix, basePath, m.url.replace(publicFilesPrefix, ""));
        return m;
      });
      return { manifest, warnings: [] };
    },
  ],
});

/** @type {import("next").NextConfig} */
const nextConfig = {
  assetPrefix,
  basePath,
  reactStrictMode: true,
};

export default withSerwist(nextConfig);
```

I've not tested this, but it should work.

**Comment by miltonlaufer** [comment]
Hey, thanks again for your response!

Unfortunately (and it might be something on my end), this didn't solve the issue: the only files inside the `public` folder the `manifestTransforms` setting catches are the Serwist generated ones (the `sw.js` and other `swe-worker-*` files). Seems that Serwist (or Workbox, not sure) transverse the `public` folder _after_ running the `manifestTransforms` callbacks. 

To give you one example: my `public` folder includes a subfolder `/Aleo-Regular/` with fonts. As we are not currently uploading the public folder to `https://mywebsite.com` but to `https://cdn.mywebsite.com`, this results in the following error (which shows the asset is pre-cached by Serwist): 

```
sw.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://mywebsite.com/Aleo-Regular/Aleo-Regular-webfont.eot","status":404}]
    at eG._handleInstall (https://mywebsite.com/sw.js:1:26205)
    at async eG._handle (https://mywebsite.com/sw.js:1:25622)
    at async eG._getResponse (https://mywebsite.com/sw.js:1:21083)
 ``` 
    
 It's worth noting, though, that _if we do the following_, then there is no attempt to cache the font:
 
 ```javascript
 exclude: [()=>true]
 ```

Although what seems weird to me is that if instead of that, we do this

```javascript
	exclude: [
		entry => {
			console.log('entry', entry?.asset?.name)
			return false
		},
	],
```

THAT font **does not appear** in the log. 

Any suggestion?

**Comment by DuCanhGH** [comment]
@miltonlaufer ah.

I forgot that `@serwist/next` adds files in the public directory to the precache list via `additionalPrecacheEntries`. Entries provided via this option do not go through `manifestTransforms`. If you specify `additionalPrecacheEntries`, `@serwist/next` will skip the step of scanning the public directory. Given the way things are, you can actually do something like this:

```js
import path from "node:path";
import crypto from "node:crypto";
import fs from "node:fs";
import { globSync } from "glob";

export const getFileHash = (file: fs.PathOrFileDescriptor) =>
  crypto.createHash("md5").update(fs.readFileSync(file)).digest("hex");

const assetPrefix = "https://example.com";
const publicDir = path.resolve("public");
const publicScan = globSync(["**/*"], {
  nodir: true,
  cwd: publicDir,
  ignore: ["swe-worker-*.js", "sw.js", "sw.js.map"],
});
const additionalPrecacheEntries = publicScan.map((f) => ({
  url: path.posix.join(assetPrefix, f),
  revision: getFileHash(path.join(publicDir, f)),
}));

const withSerwist = withSerwistInit({
  cacheOnNavigation: true,
  swSrc: "app/sw.ts",
  swDest: "public/sw.js",
  additionalPrecacheEntries,
});

/** @type {import("next").NextConfig} */
const nextConfig = {
  assetPrefix,
  reactStrictMode: true,
};

export default withSerwist(nextConfig);
```

Hope this helps!

**Comment by miltonlaufer** [comment]
Hey, thanks a lot, this did the trick! 

Only thing I needed to change was this:

```javascript
const additionalPrecacheEntries = publicScan.map(f => {
	return {
		url: assetPrefix.replace(/\/+$/, '') + '/' + f.replace(/^\/+/, ''), //this line
		revision: getFileHash(path.join(publicDir, f)),
	}
})
```

The other one was creating urls like `https:/cdn.mywebsite.com/images/myimage.png` (note the single `/` after `https:`), which ended up being parsed like `https://www.mywebsite.com/cdn.mywebsite.com/images/myimage.png` and getting a 404. 

Let me know if you want me to open a PR adding some feature to include this in the configuration (shouldn't be that hard, I think). 

Anyway, thanks again!

**Comment by DuCanhGH** [comment]
@miltonlaufer 

> The other one was creating urls like `https:/cdn.mywebsite.com/images/myimage.png` (note the single `/` after `https:`), which ended up being parsed like `https://www.mywebsite.com/cdn.mywebsite.com/images/myimage.png` and getting a 404. 

I forgot that `path.join` doesn't understand the `http://` part of the URL. In your case, you can also use `new URL` :)

> Let me know if you want me to open a PR adding some feature to include this in the configuration (shouldn't be that hard, I think). 

Not really. I plan to introduce a v10 breaking change to `@serwist/(next|webpack-plugin)@9.1.0` via flags so that we no longer need to use `additionalPrecacheEntries` to pass the entries in the public directory. Not sure how this would actually be implemented though, since we rely on the `compilation` object to determine the list of precache entries.

**Comment by miltonlaufer** [comment]
Doki, thanks again! (I was about to offer at least to add some of this stuff to the documentation, but seems you have everything covered.)

**Comment by DuCanhGH** [comment]
@miltonlaufer 

> I was about to offer at least to add some of this stuff to the documentation, but seems you have everything covered.

I... am not so sure about that, but cool :)
