### ISSUE TITLE
[Bug]:  @serwist/nuxt get started error

### ISSUE THREAD

**Issue by keven1024** [serwist/serwist#247]
### Provide environment information

```
"dependencies": {
    "nuxt": "^3.16.0",
    "vue": "latest",
    "vue-router": "latest"
  },
  "packageManager": "pnpm@9.11.0+sha512.0a203ffaed5a3f63242cd064c8fb5892366c103e328079318f78062f24ea8c9d50bc6a47aa3567cabefd824d170e78fa2745ed1f16b132e16436146b7688f19b",
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.13.2",
    "@serwist/build": "^9.0.12",
    "@serwist/nuxt": "^9.0.12",
    "@vueuse/core": "^13.0.0",
    "@vueuse/nuxt": "^13.0.0",
    "serwist": "^9.0.12"
  }
```

### Which project is this issue for?

@serwist/nuxt

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://codesandbox.io/p/devbox/7l4pk5

### To reproduce

Follow the official documentation: https://serwist.pages.dev/docs/nuxt/getting-started

### Describe the bug

Not working

### Expected behavior

Normal operation

### Screenshots (if relevant)

```
 Cannot start nuxt:  Received an invalid @serwist/vite configuration: {                                            nuxi  18:03:03
  "_errors": [],
  "swSrc": {
    "_errors": [
      "Received invalid type: expected string, received undefined."
    ]
  }
}

    "_errors": [],
    "swSrc": {
    "_errors": [
    "Received invalid type: expected string, received undefined."
    ]
    }
    }
    at validateInjectManifestOptions (/Users/fan/015/node_modules/.pnpm/@serwist+vite@9.0.12_typescript@5.8.2_vite@6.2.2_@types+node@22.13.10_jiti@2.4.2_terser@5.39.0_yaml@2.7.0_/node_modules/@serwist/vite/dist/index.js:238:15)
    at async resolveOptions (/Users/fan/015/node_modules/.pnpm/@serwist+vite@9.0.12_typescript@5.8.2_vite@6.2.2_@types+node@22.13.10_jiti@2.4.2_terser@5.39.0_yaml@2.7.0_/node_modules/@serwist/vite/dist/index.js:320:158)
    at async configResolved (/Users/fan/015/node_modules/.pnpm/@serwist+vite@9.0.12_typescript@5.8.2_vite@6.2.2_@types+node@22.13.10_jiti@2.4.2_terser@5.39.0_yaml@2.7.0_/node_modules/@serwist/vite/dist/index.js:361:27)
    at async Promise.all (index 1)
    at async resolveConfig (/Users/fan/015/node_modules/.pnpm/vite@6.2.2_@types+node@22.13.10_jiti@2.4.2_terser@5.39.0_yaml@2.7.0/node_modules/vite/dist/node/chunks/dep-B0fRCRkQ.js:54308:3)
    at async _createServer (/Users/fan/015/node_modules/.pnpm/vite@6.2.2_@types+node@22.13.10_jiti@2.4.2_terser@5.39.0_yaml@2.7.0/node_modules/vite/dist/node/chunks/dep-B0fRCRkQ.js:43845:18)
    at async buildClient (/Users/fan/015/node_modules/.pnpm/@nuxt+vite-builder@3.16.0_@types+node@22.13.10_magicast@0.3.5_rollup@4.36.0_terser@5.39.0_typ_fz3yrl6gzsaqcao3ju5yjb7t2q/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.0lB6n6pu.mjs:696:24)
    at async withLogs (/Users/fan/015/node_modules/.pnpm/@nuxt+vite-builder@3.16.0_@types+node@22.13.10_magicast@0.3.5_rollup@4.36.0_terser@5.39.0_typ_fz3yrl6gzsaqcao3ju5yjb7t2q/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.0lB6n6pu.mjs:1507:3)
    at async bundle (/Users/fan/015/node_modules/.pnpm/@nuxt+vite-builder@3.16.0_@types+node@22.13.10_magicast@0.3.5_rollup@4.36.0_terser@5.39.0_typ_fz3yrl6gzsaqcao3ju5yjb7t2q/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.0lB6n6pu.mjs:1498:3)
    at async bundle (/Users/fan/015/node_modules/.pnpm/nuxt@3.16.0_@parcel+watcher@2.5.1_@types+node@22.13.10_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5_sna5qyxcgghtpapy4oabm4mrvy/node_modules/nuxt/dist/shared/nuxt.B7-cu52A.mjs:7234:5)
```

**Comment by DuCanhGH** [comment]
Umm... oops! It's actually either service-worker.{ts,js} or service-worker/index.{ts,js} by default for `@serwist/nuxt` (as there seems to be no way to require users to supply options with Nuxt modules). Will fix that soon!

**Comment by keven1024** [comment]
> Umm... oops! It's actually either service-worker.{ts,js} or service-worker/index.{ts,js} by default for `@serwist/nuxt` (as there seems to be no way to require Nuxt module users to supply certain options). Will fix that soon!


Thanks, I renamed `sw.ts` to `service-worker.ts` and it worked
![Image](https://github.com/user-attachments/assets/bbd90246-3ec7-4dcb-89c0-a2f92aa409ca)
If you can, please change the documentation sw.js to `service-worker.ts`

**Comment by DuCanhGH** [comment]
Fixed :)

**Comment by jedifunk** [comment]
this is not fixed. the site still says sw.ts and i can't for the life of me figure out how to get just the baseline service worker going.

is it service-worker.ts? is it sw.ts? does it go in /public? does it go in the root?

documentation really lacking

**Comment by DuCanhGH** [comment]
@jedifunk the source code for the docs is fixed, but I forgot to deploy it. It's service-worker.ts by default, not sw.ts, but you can change it if you want to. It's a TypeScript file, so no, you don't put in the public directory. Put it in your project's root directory. You can also do service-worker/index.ts if you want.
